config/routes.rb
Rails.application.routes.draw do
  
 resources :lists do
   resources :lists_item do
    member do
     patch :complete
    end
  end
end
  
  root "lists#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :lists_item
end

app/models/lists_item.rb
class ListsItem < ApplicationRecord
  belongs_to :list

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:title, :description)
    end
end

app/controllers/lists_item_controller.rb
class ListsItemController < ApplicationController
    before_action :set_lists
    before_action :set_lists_item, except: [:create]

    def create
        @lists_item = @lists.lists_item.create(lists_item_params)
        redirect_to @lists
    end

    def destroy
        @lists_item = @lists.lists_item.find(params[:id])
        if @lists_item.destroy
        flash[:success] = "A tarefa foi deletada."
        else
        flash[:error] = "A tarefa não pode ser deletada"
    end

    def complete
        @lists_item.update_attribute(:completed_at, Time.now)
        redirect_to @lists_item, notice: "Tarefa completa"
    end
    
    private

    def set_lists_item
        @lists_item = todolist.find(params[:lists_item_id])
    end
    
    def lists_item_params
        params[:lists_item].permit(:content)
    end 
    

    def set_lists_item
        @lists_item = @lists_item.lists_item.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/lists_item_helper.rb
module ListsItemHelper
end

app/views/layouts/_form.html.erb
<%= form_for([@lists, @lists.lists_item.build]) do |f| %>
 <%= f.text_field :content, placeholder: "Nova Tarefa" %>
 <%= f.submit %>
<% end %>

app/views/layouts/_lists_item.html.erb
<div class="row clearfix">
<p><%= lists_item.content %></p>
<%= link_to lists_lists_item_path(@lists, lists_item.id), method: :delete, data: { confirm: "Tem certeza?" } %>

<%= link_to "Completo", complete_lists_lists_item_path(@lists, lists_item.id), method: :patch %>

</div>
  <div class="lists_items">
   <p style="opacity: 0.4;"><strike><%= lists_items.content %></strike></p>
  </div>
  <div class="trash">
   <%= link_to "Delete", lists_lists_items_path(@lists, lists_items.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
 <% else %>
  <div class="complete">
   <%= link_to "Mark as Complete", complete_lists_lists_items_path(@lists, lists_items.id), method: :patch %>
  </div>
  <div class="lists_items">
   <p><%= lists_items.content %></p>
  </div>
  <div class="trash">
   <%= link_to "Delete", lists_lists_items_path(@lists, lists_items.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Titulo' %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label 'Descrição' %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Criar tarefa' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editar</h1>

<%= render 'form', list: @list %>

<%= link_to 'Exibir', @list %> |
<%= link_to 'Voltar', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Tarefas</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.title %></td>
        <td><%= list.description %></td>
        <td><%= link_to 'Exibir', list %></td>
        <td><%= link_to 'Editar', edit_list_path(list) %></td>
        <td><%= link_to 'Deletar', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Tarefa', new_list_path %>

app/views/lists/new.html.erb
<h1>Nova tarefa</h1>

<%= render 'form', list: @list %>

<%= link_to 'Voltar', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @list.title %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @list.description %>
</p>

<div id="lists_item_wrapper">
 <%= render @list.lists_item %>
 <div id="form">
  <%= render "lists_item/form" %>
 </div>
</div>

<%= link_to 'Editar', edit_list_path(@list) %> |
<%= link_to 'Voltar', lists_path %>